"""Add subscription plans and features columns

Revision ID: 359ad21464e6
Revises: e6488fb38b7b
Create Date: 2026-02-16 21:05:39.612413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '359ad21464e6'
down_revision: Union[str, None] = 'e6488fb38b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
