"""add subscription plans and features

Revision ID: e6488fb38b7b
Revises: 4b930e4e8e04
Create Date: 2026-02-16 19:45:00.780566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6488fb38b7b'
down_revision: Union[str, None] = '4b930e4e8e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
